// Builds index.html (the GitHub Pages site) from off-script.html (the page body,
// which is also what gets published as the Claude artifact).
// Usage: node build.mjs
import { readFileSync, writeFileSync } from "node:fs";

const src = readFileSync("off-script.html", "utf8");
const cut = src.indexOf("</style>") + "</style>".length;
const head = src.slice(0, cut).replace(/^<meta charset="utf-8">\n?/, "");
const body = src.slice(cut);

writeFileSync("index.html", `<!doctype html>
<!-- Generated by build.mjs from off-script.html. Edit that file, then run: node build.mjs -->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<meta name="description" content="A personal Netflix US picker that ignores popularity and learns what you don't want.">
<style>
:root{padding-top:env(safe-area-inset-top,0px);padding-bottom:env(safe-area-inset-bottom,0px)}
body{margin:0}
img{max-width:100%}
[hidden]{display:none!important}
</style>
${head}
</head>
<body>${body}
</body>
</html>
`);
console.log("Wrote index.html");
